#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-3"
commonLabels:
  component: orb-3
  group: core
  project: trustbloc

configMapGenerator:
- behavior: merge
  envs:
  - orb/config.env
  name: orb-env

secretGenerator:
- behavior: merge
  envs:
  - orb/secret.env
  name: orb-env-secret

vars:
- fieldref:
    fieldPath: metadata.name
  name: SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: orb

components:
  - ../../../components/mq

resources:
- ../../../base

transformers:
- sedtransform.yml
- sedb64transform.yml
