#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: uni-resolver-did-v1-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-resolver-did-v1-driver
  template:
    metadata:
      labels:
        app: uni-resolver-did-v1-driver
    spec:
      containers:
      - name: uni-resolver-did-v1-driver
        image: uni-resolver-did-v1-driver:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
            name: http-port
        resources: {}
status: {}
