#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

vars:
- fieldref:
    fieldPath: metadata.name
  name: SERVER_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: wallet-support

configMapGenerator:
- envs:
  - config.env
  name: server-env

secretGenerator:
- envs:
  - secret.env
  name: server-env-secret
- literals:
  - auth.key=5QWpW+aj7WTNzEdZmTcOXXlWP78Z49CmcS9T9Bn4nx0=
  - enc.key=ccKjwMDwhXzanvKJUVSMHPGYQ9OdBqAb3Ywg7hv58qY=
  name: server-keys

resources:
- deployment.yml
- service.yml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: wallet-server
  newName: ghcr.io/trustbloc-cicd/wallet-server
  newTag: v0.1.7-snapshot-db25185
