#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: edge-sandbox-

commonLabels:
  component: vcs
  group: core
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  envs:
  - vcs/config.env
  name: vcs-env
- behavior: replace
  files:
  - vcs/profiles.json
  name: vcs-profile-config

secretGenerator:
- behavior: merge
  envs:
  - vcs/secret.env
  name: vcs-env-secret

transformers:
- sedtransform.yml
- sedb64transform.yml

resources:
- ../../base
