#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

providers:
  mockbank:
    url: https://hydra.||DOMAIN||/
    clientID: hub-auth
    clientSecret: hub-auth-secret
    name: Demo OIDC
    signUpText: Demo Sign-Up Partner
    signInText: Demo Sign-In Partner
#    logoURL: https://hub-auth.||DOMAIN||/static/images/demo_provider.svg
    logoURL: https://upload.wikimedia.org/wikipedia/en/a/a4/Universal_Bank.svg
