#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

vars:
- fieldref:
    fieldPath: metadata.name
  name: ROUTER_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: router
- fieldref:
    fieldPath: metadata.name
  name: ROUTER_WS_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: router-ws
- fieldref:
    fieldPath: metadata.name
  name: ROUTER_API_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: router-api


configMapGenerator:
- envs:
  - config.env
  name: router-env

secretGenerator:
- envs:
  - secret.env
  name: router-env-secret

resources:
- deployment.yml
- service.yml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hub-router
  newName: ghcr.io/trustbloc/hub-router
  newTag: 0.1.7
